// Disclaimer: This file was generated using AI
// Comprehensive list of world currencies
export const currencies = [
  { code: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  { code: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", flag: "🇵🇱" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪", flag: "🇮🇱" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", flag: "🇮🇸" },
  { code: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", flag: "🇸🇦" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", flag: "🇶🇦" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", flag: "🇰🇼" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", flag: "🇧🇭" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", flag: "🇴🇲" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", flag: "🇯🇴" },
  { code: "LBP", name: "Lebanese Pound", symbol: "£", flag: "🇱🇧" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", flag: "🇪🇬" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", flag: "🇹🇳" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
  { code: "BWP", name: "Botswana Pula", symbol: "P", flag: "🇧🇼" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", flag: "🇸🇨" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", flag: "🇱🇰" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", flag: "🇧🇹" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: ".ރ", flag: "🇲🇻" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", flag: "🇮🇷" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶" },
  { code: "SYP", name: "Syrian Pound", symbol: "£", flag: "🇸🇾" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "лв", flag: "🇰🇬" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", flag: "🇹🇲" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "лв", flag: "🇺🇿" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", flag: "🇲🇳" },
  { code: "LAK", name: "Lao Kip", symbol: "₭", flag: "🇱🇦" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", flag: "🇧🇳" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", flag: "🇫🇯" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", flag: "🇸🇧" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", flag: "🇻🇺" },
  { code: "WST", name: "Samoan Tala", symbol: "WS$", flag: "🇼🇸" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "$b", flag: "🇧🇴" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  { code: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/.", flag: "🇵🇪" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "Gs", flag: "🇵🇾" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs", flag: "🇻🇪" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", flag: "🇬🇾" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", flag: "🇸🇷" },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    flag: "🇹🇹",
  },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", flag: "🇯🇲" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", flag: "🇧🇧" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", flag: "🇧🇸" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", flag: "🇳🇮" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
  { code: "CUP", name: "Cuban Peso", symbol: "₱", flag: "🇨🇺" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
];

// Get currency by code
export const getCurrencyByCode = (code) => {
  return currencies.find((currency) => currency.code === code) || currencies[0];
};

// Format currency amount
export const formatCurrency = (amount, currencyCode = "USD") => {
  const currency = getCurrencyByCode(currencyCode);

  // Special formatting for certain currencies
  const formatOptions = {
    style: "currency",
    currency: currencyCode,
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  };

  // Some currencies don't need decimal places
  if (["JPY", "KRW", "VND", "IDR", "CLP", "PYG"].includes(currencyCode)) {
    formatOptions.minimumFractionDigits = 0;
    formatOptions.maximumFractionDigits = 0;
  }

  try {
    return new Intl.NumberFormat("en-US", formatOptions).format(amount);
  } catch {
    // Fallback formatting if currency is not supported by Intl
    return `${currency.symbol}${amount.toLocaleString()}`;
  }
};

// Currency conversion rates (in a real app, this would come from an API)
export const exchangeRates = {
  USD: 1.0,
  EUR: 0.85,
  GBP: 0.73,
  JPY: 110.0,
  AUD: 1.35,
  CAD: 1.25,
  CHF: 0.92,
  CNY: 6.45,
  SEK: 8.5,
  NZD: 1.42,
  MXN: 20.0,
  SGD: 1.35,
  HKD: 7.8,
  NOK: 8.6,
  KRW: 1180.0,
  TRY: 8.5,
  RUB: 75.0,
  INR: 74.0,
  BRL: 5.2,
  ZAR: 14.5,
  PLN: 3.8,
  ILS: 3.3,
  DKK: 6.3,
  CZK: 21.5,
  HUF: 295.0,
  RON: 4.2,
  BGN: 1.66,
  HRK: 6.4,
  ISK: 125.0,
  THB: 31.0,
  MYR: 4.1,
  IDR: 14200.0,
  PHP: 50.0,
  VND: 23000.0,
  AED: 3.67,
  SAR: 3.75,
  QAR: 3.64,
  KWD: 0.3,
  BHD: 0.38,
  OMR: 0.38,
  JOD: 0.71,
  LBP: 1500.0,
  EGP: 15.7,
  MAD: 9.0,
  TND: 2.8,
  DZD: 135.0,
  NGN: 410.0,
  GHS: 6.0,
  KES: 110.0,
  UGX: 3600.0,
  TZS: 2300.0,
  ETB: 44.0,
  ZMW: 16.0,
  BWP: 11.0,
  MUR: 40.0,
  SCR: 13.5,
  PKR: 170.0,
  LKR: 200.0,
  BDT: 85.0,
  NPR: 118.0,
  BTN: 74.0,
  MVR: 15.4,
  AFN: 80.0,
  IRR: 42000.0,
  IQD: 1460.0,
  SYP: 2500.0,
  YER: 250.0,
  GEL: 3.1,
  AMD: 520.0,
  AZN: 1.7,
  KZT: 425.0,
  KGS: 85.0,
  TJS: 11.3,
  TMT: 3.5,
  UZS: 10600.0,
  MNT: 2850.0,
  LAK: 9500.0,
  KHR: 4100.0,
  MMK: 1400.0,
  BND: 1.35,
  TWD: 28.0,
  FJD: 2.1,
  PGK: 3.5,
  SBD: 8.0,
  VUV: 110.0,
  WST: 2.6,
  TOP: 2.3,
  ARS: 100.0,
  BOB: 6.9,
  CLP: 800.0,
  COP: 3800.0,
  PEN: 4.0,
  UYU: 44.0,
  PYG: 6900.0,
  VES: 4.0,
  GYD: 209.0,
  SRD: 14.3,
  TTD: 6.8,
  JMD: 150.0,
  BBD: 2.0,
  BSD: 1.0,
  BZD: 2.0,
  GTQ: 7.7,
  HNL: 24.0,
  NIO: 35.0,
  CRC: 620.0,
  PAB: 1.0,
  CUP: 24.0,
  DOP: 57.0,
  HTG: 90.0,
};

// Convert amount from one currency to another
export const convertCurrency = (amount, fromCurrency, toCurrency) => {
  if (fromCurrency === toCurrency) return amount;

  const fromRate = exchangeRates[fromCurrency] || 1;
  const toRate = exchangeRates[toCurrency] || 1;

  // Convert to USD first, then to target currency
  const usdAmount = amount / fromRate;
  return usdAmount * toRate;
};
